### ISSUE TITLE
background-size兼容IE7、8

### ISSUE THREAD

**Issue by chen77** [chen77/CSS-Hack#1]
## background-size兼容IE7、8
**方法一**

``` css
filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(
src='images/logo.gif',
sizingMethod='scale');

-ms-filter: "progid:DXImageTransform.Microsoft.AlphaImageLoader(
src='images/logo.gif',
sizingMethod='scale')";
```
- 不能指定任意大小background百分比，可用cover，
- 用于单张图片不能使用图片精灵等拼图，
- 要引用绝对路径图片，
- 兼容ie8，ie7的兼容效果不好

**方法二**
引用htc文件，[htc源文件地址](https://github.com/louisremi/background-size-polyfill)

``` css
.selector {
 background-size: cover;
 behavior: url(/backgroundsize.min.htc);
 -ms-behavior: url(/backgroundsize.min.htc);
 }
```
- 可指定百分比，
- .htc要相对文档路径，
- 兼容ie7，8

**Comment by chen77** [comment]
## 背景透明文字不透明 
**方法一：**

``` css
.top{
    height: 30px;
    line-height: 30px;
    background-color:rgba(22,133,229,.3);   
}

/*IE9既支持rgba属性又支持alpha属性会形成双重透明*/
@media \0screen\,screen\9 {/* 只支持IE6、7、8 */
    .top{
        background-color:#1685e5;
/* 若rgba(0,0,0,.3)IE6和部分IE7内核的浏览器(如QQ浏览器)会读懂，但解析为透明 */
        filter:alpha(opacity=30);
       position:static;
        *zoom: 1;/* 激活IE6、7的haslayout属性，让它读懂Alpha */
    }
}
.top-nav{
    position: relative;//背景层以上部分相对定位，使文字不透明
}
```

**方法二：**
直接用两个DIV绝对定位放在同一个位置设置层级关系，
此方法需要使用多层定位并会出现空的标签不够友好。

> **参考文章：[CSS实现背景透明，文字不透明，兼容所有浏览器](http://www.cnblogs.com/PeunZhang/p/4089894.html)**

方法一背景层用了绝对定位则不兼容IE7

**Comment by chen77** [comment]
## 复选框单选框与文字对齐
在参考文章里可以找到作者列出的很多方法，但是demo测试下来以下是**性价比较高的方法**

``` css
.checkbox{
vertical-align: -2px;
}
```

> 参考文章[checkbox复选框的一些深入研究与理解](http://www.zhangxinxu.com/wordpress/2009/12/checkbox%E5%A4%8D%E9%80%89%E6%A1%86%E7%9A%84%E4%B8%80%E4%BA%9B%E6%B7%B1%E5%85%A5%E7%A0%94%E7%A9%B6%E4%B8%8E%E7%90%86%E8%A7%A3/)（可以深入了解checkbox的表现形式）

**Comment by chen77** [comment]
## img图片底部出现莫名的下边距问题
> 图片底部的空隙实际上涉及行内元素的布局模型，图片默认的垂直对齐方式是基线，而基线的位置是与字体相关的。所以在某些时候，图片底部的空隙可能是 2px，而有时可能是 4px 或更多。不同的 font-size 应该也会影响到这个空隙的大小。

**解决办法：**
给img定义vertical-align或者display：block;，最优的解决办是定义vertical-align，
注：定义vertical-align为middle时在IE6中大概还有一像素的顶边距，最好为top或bottom。
当然还有种极端解决办法大家可以试试就是将父容器的字体大小为零，font-size:0

**Comment by chen77** [comment]
## 滚动条美化css
Webkit浏览器，比如谷歌浏览器下

``` css
    ::-webkit-scrollbar {
          width: 15px;
    } /* 这是针对缺省样式 (必须的) */

       ::-webkit-scrollbar-track {
          background-color: #b46868;
    } /* 滚动条的滑轨背景颜色 */

    ::-webkit-scrollbar-thumb {
          background-color: rgba(0, 0, 0, 0.2); 
    } /* 滑块颜色 */

    ::-webkit-scrollbar-button {
          background-color: #7c2929;
    } /* 滑轨两头的监听按钮颜色 */

    ::-webkit-scrollbar-corner {
          background-color: black;
    } /* 横向滚动条和纵向滚动条相交处尖角的颜色 */
```

IE火狐浏览器滚动条的美化可使用相关插件。

**Comment by chen77** [comment]
## 清除浮动备忘
``` css
.clear{
    *zoom:1;
}
.clear:after{
    visibility:hidden;
    content:"";
    display:block;
    clear:both;
    height:0;
}
```

**Comment by chen77** [comment]
## 文字内容溢出用(…)省略号表示
只针对一行文字，多列文字不可行
``` css
.text-overflow{
width:12em; 
white-space:nowrap; //文本不会换行，文本会在在同一行上继续，直到遇到 br 标签为止
overflow:hidden; //超出宽度后隐藏
text-overflow:ellipsis;//显示省略符号来代表被修剪的文本
}
```
