### ISSUE TITLE
常见样式bug重置

### ISSUE THREAD

**Issue by chen77** [chen77/CSS-Hack#10]
## 布局时避免因border&&padding值的重计算[box-sizing属性](http://zh.learnlayout.com/box-sizing.html)

``` css
*{
   -webkit-box-sizing: border-box;
       -moz-box-sizing: border-box;
            box-sizing: border-box;
  }
```

**Comment by chen77** [comment]
## 除输入框内阴影,及input[type="submit"]和input[type="reset"]的重渲染

在iOS上，输入框默认有内部阴影，但无法使用 box-shadow 来清除，如果不需要阴影，可以这样关闭：

``` css
input,textarea {
    border: 0; /* 方法1 */
    -webkit-appearance: none; /* 方法2 */
}
```

![渲染前](http://7xpwoc.com1.z0.glb.clouddn.com/webapp02-1.png)![渲染后](http://7xpwoc.com1.z0.glb.clouddn.com/webapp02-2.png)

**Comment by chen77** [comment]
## 使用 a标签做按钮及input输入框点击时会出现一个“暗色”的背景，去掉该背景的方法如下

``` css
a,button,input,optgroup,select,textarea {
    -webkit-tap-highlight-color:rgba(0,0,0,0);
 /*去掉a、input和button点击时的蓝色外边框和灰色半透明背景*/
}
```

**Comment by chen77** [comment]
## 禁止长按 a，img 标签长按出现菜单栏

``` css
a, img {
    -webkit-touch-callout: none; /*禁止长按链接与图片弹出菜单*/
}
```
