### ISSUE TITLE
除输入框内阴影,及input[type="submit"]和input[type="reset"]的重渲染

### ISSUE THREAD

**Issue by chen77** [chen77/CSS-Hack#11]
在iOS上，输入框默认有内部阴影，但无法使用 box-shadow 来清除，如果不需要阴影，可以这样关闭：

``` css
input,textarea {
    border: 0; /* 方法1 */
    -webkit-appearance: none; /* 方法2 */
}
```

![渲染前](http://7xpwoc.com1.z0.glb.clouddn.com/webapp02-1.png)![渲染后](http://7xpwoc.com1.z0.glb.clouddn.com/webapp02-2.png)
