### ISSUE TITLE
禁止长按 a，img 标签长按出现菜单栏

### ISSUE THREAD

**Issue by chen77** [chen77/CSS-Hack#13]
``` css
a, img {
    -webkit-touch-callout: none; /*禁止长按链接与图片弹出菜单*/
}
```
