### ISSUE TITLE
背景透明文字不透明

### ISSUE THREAD

**Issue by chen77** [chen77/CSS-Hack#2]
**方法一：**

``` css
.top{
    height: 30px;
    line-height: 30px;
    background-color:rgba(22,133,229,.3);   
}

/*IE9既支持rgba属性又支持alpha属性会形成双重透明*/
@media \0screen\,screen\9 {/* 只支持IE6、7、8 */
    .top{
        background-color:#1685e5;
/* 若rgba(0,0,0,.3)IE6和部分IE7内核的浏览器(如QQ浏览器)会读懂，但解析为透明 */
        filter:alpha(opacity=30);
        *zoom: 1;/* 激活IE6、7的haslayout属性，让它读懂Alpha */
    }
}
.top-nav{
    position: relative;//背景层以上部分相对定位，使文字不透明
}
```

**方法二：**
直接用两个DIV绝对定位放在同一个位置设置层级关系，
此方法需要使用多层定位并会出现空的标签不够友好。

> **参考文章：[CSS实现背景透明，文字不透明，兼容所有浏览器](http://www.cnblogs.com/PeunZhang/p/4089894.html)**
