### ISSUE TITLE
复选框单选框与文字对齐

### ISSUE THREAD

**Issue by chen77** [chen77/CSS-Hack#3]
在参考文章里可以找到作者列出的很多方法，但是demo测试下来以下是**性价比较高的方法**

``` css
.checkbox{
vertical-align: -2px;
}
```

> 参考文章[checkbox复选框的一些深入研究与理解](http://www.zhangxinxu.com/wordpress/2009/12/checkbox%E5%A4%8D%E9%80%89%E6%A1%86%E7%9A%84%E4%B8%80%E4%BA%9B%E6%B7%B1%E5%85%A5%E7%A0%94%E7%A9%B6%E4%B8%8E%E7%90%86%E8%A7%A3/)（可以深入了解checkbox的表现形式）
