### ISSUE TITLE
图片居中问题处理

### ISSUE THREAD

**Issue by chen77** [chen77/CSS-Hack#4]
## 图片水平居中
- **直接元素本身设置**

``` css
.img{
display:block;//设置为块状元素
margin:0 auto;//左右居中
}
```
- **通过父元素设置**

``` css
.img-box{
text-align:center;
}
```

**Comment by chen77** [comment]
## 图片水平垂直居中①

``` html
<div class="box">
    <img src="1.gif"/>
    <span></span>   
</div>
```

``` css
.box{
width: 800px;
height: 800px;
border: 3px solid yellow;
text-align: center;/*这个是让内部文字(行内元素)水平居中*/
}
img{
vertical-align: middle;
/*把img的标线设置为正中这个时候正中和span的正中对齐，*/
/*也就和父元素的正中对齐，于是垂直居中了*/
}
span{
display:inline-block;
height: 100%;/*把span的高度设置为父元素的高度*/
vertical-align: middle;
/*水平对其的标线设置为正中间*/
/*由于子元素高度和父元素相同，所以span的正中间就是父元素正中*/
}

```

**使用注意**
- span内部不能有任何东西，包括空格换行符
- span和img之间不能有任何东西

> 参考[关于让一个未知宽高的img在一个div中居中的问题？](https://www.zhihu.com/question/37487659#answer-25494145)

**Comment by chen77** [comment]
## 图片水平垂直居中②-使用absolute定位居中

``` css
.middle{
position:absolute;
top:0;left:0;right:0;bottom:0;
margin:auto;
display:block;
/*使用这个方法需要将该元素的父元素设置为static以外的值,外容器必须设定显视高度height/min-height*/
}
```

**Comment by chen77** [comment]
## 图片水平垂直居中③-使用table-cell居中

使用`display:table-cell`可以实现水平垂直居中，但需要额外添加元素作为外容器

``` css
.img-wrapper{
display:table-cell;
text-align:center;
vertical-align:center;
}
```
