### ISSUE TITLE
滚动条美化css

### ISSUE THREAD

**Issue by chen77** [chen77/CSS-Hack#6]
Webkit浏览器，比如谷歌浏览器下

``` css
    ::-webkit-scrollbar {
          width: 15px;
    } /* 这是针对缺省样式 (必须的) */

       ::-webkit-scrollbar-track {
          background-color: #b46868;
    } /* 滚动条的滑轨背景颜色 */

    ::-webkit-scrollbar-thumb {
          background-color: rgba(0, 0, 0, 0.2); 
    } /* 滑块颜色 */

    ::-webkit-scrollbar-button {
          background-color: #7c2929;
    } /* 滑轨两头的监听按钮颜色 */

    ::-webkit-scrollbar-corner {
          background-color: black;
    } /* 横向滚动条和纵向滚动条相交处尖角的颜色 */
```

IE火狐浏览器滚动条的美化可使用相关插件。
