### ISSUE TITLE
清除浮动备忘

### ISSUE THREAD

**Issue by chen77** [chen77/CSS-Hack#7]
``` css
.clear{
    *zoom:1;
}
.clear:after{
    visibility:hidden;
    content:"";
    display:block;
    clear:both;
    height:0;
}
```
