### ISSUE TITLE
文字内容溢出用(…)省略号表示

### ISSUE THREAD

**Issue by chen77** [chen77/CSS-Hack#8]
``` css
.text-overflow{
width:12em; 
white-space:nowrap; //文本不会换行，文本会在在同一行上继续，直到遇到 br 标签为止
overflow:hidden; //超出宽度后隐藏
text-overflow:ellipsis;//显示省略符号来代表被修剪的文本
}
```
